name: Build checks
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Retrieve required node version
        run: |
          echo "engine_node_version=$(jq -r '.engines.node' package.json)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.engine_node_version }}
      - run: npm ci
      - run: npm run lint
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Retrieve required node version
        run: |
          echo "engine_node_version=$(jq -r '.engines.node' package.json)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.engine_node_version }}
      - run: npm ci
      - run: npm run build